blakeblackshear/frigate-hass-integration

custom_components/frigate/const.py

Fixes https://github.com/blakeblackshear/frigate/discussions/510

fix: cat icon should be mdi:cat (cat-side missing)

---

.gitignore

Motivation: git is being enthusiastic about things it should not be enthusiastic about!

Add some additional stock entries to .gitignore

---

custom_components/frigate/__init__.py
custom_components/frigate/binary_sensor.py
custom_components/frigate/manifest.json
requirements.txt
requirements_dev.txt
tests/__init__.py
tests/conftest.py
tests/test_binary_sensor.py

Tests and code readability improvements for binary_sensor .
After this change:
```
Name                                         Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------
custom_components/frigate/__init__.py           50      5    90%   82-88, 93
custom_components/frigate/api.py                59     39    34%   23-24, 28-29, 33-36, 40-43, 47-48, 52-53, 59-98
custom_components/frigate/binary_sensor.py      67      0   100%
custom_components/frigate/camera.py            109     14    87%   85, 100-106, 110-112, 141, 153-154, 198, 209
custom_components/frigate/config_flow.py        29      0   100%
custom_components/frigate/const.py              24      0   100%
custom_components/frigate/media_source.py      218    218     0% …
```

Test Coverage #2: binary_sensor

---

.devcontainer/configuration.yaml
.devcontainer/frigate.yml
.github/workflows/hassfest.yaml
.pre-commit-config.yaml
custom_components/__init__.py
custom_components/frigate/api.py
custom_components/frigate/binary_sensor.py
custom_components/frigate/camera.py
custom_components/frigate/config_flow.py
custom_components/frigate/media_source.py
custom_components/frigate/sensor.py
custom_components/frigate/switch.py
custom_components/frigate/views.py
docker-compose.yml
pyproject.toml
requirements.txt
requirements_dev.txt
setup.cfg
tests/__init__.py
tests/conftest.py
tests/test_binary_sensor.py
tests/test_config_flow.py

This adds a pre-commit heavily based on the stock Home Assistant Core settings, and then applies it to all source. Very little of consequence changes here, but this should make future changes much easier to keep in style. In a few places I had to add '# noqa' exceptions to make the pre-commit pass, I'll tidy those up as I add tests to those files.
`media_source.py` is probably worth more of a review, as I had to change variable names and a glob import there.
I tested this manually via my own HA instance, the old fashioned way.
@blakeblackshear -- apologies for this hopefully one-time messy PR to get/enforce stylistic compliance, as per your stated  desire to move towards HA Core.

Add pre-commit and adjust to conform to Home Assistant style

---

custom_components/frigate/switch.py
pyproject.toml
tests/__init__.py
tests/test_switch.py

Refactoring and tests for switch.
```
----------- coverage: platform linux, python 3.8.5-final-0 -----------
Name                                         Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------
custom_components/frigate/__init__.py           57      5    91%   99-105, 110
custom_components/frigate/api.py                61     43    30%   24-25, 29-30, 42-55, 59-64, 68-69, 73-74, 84-130
custom_components/frigate/binary_sensor.py      67      0   100%
custom_components/frigate/camera.py            109     14    87%   98, 103-109, 113-115, 148, 160-161, 206, 218
custom_components/frigate/config_flow.py        29      0   100%
custom_components/frigate/const.py              24      0   100% …
```

Test Coverage #3: switch

---

tests/test_init.py

Add tests for the `__init__,py` code that doesn't feature in other tests.
```
collecting ... 
tests/test_api.py ✓✓✓✓✓✓✓                                                                                                                                                                    16% █▋        
tests/test_binary_sensor.py ✓✓✓✓                                                                                                                                                             25% ██▌       
tests/test_camera.py ✓✓✓✓                                                                                                                                                                    34% ███▌      
tests/test_config_flow.py ✓✓✓ …
```

Test Coverage #8: __init__.py 

---

custom_components/frigate/__init__.py
custom_components/frigate/media_source.py
custom_components/frigate/views.py
tests/__init__.py
tests/test_api.py
tests/test_views.py

Refactoring and tests for `views.py`.
```
collecting ... 
tests/test_api.py ✓✓✓✓✓✓✓                                                                                                                                                                    14% █▍        
tests/test_binary_sensor.py ✓✓✓✓                                                                                                                                                             22% ██▎       
tests/test_camera.py ✓✓✓✓                                                                                                                                                                    29% ██▉       
tests/test_config_flow.py ✓✓✓ …
```

Test Coverage #9: views.py (100% edition)

---

custom_components/frigate/api.py
custom_components/frigate/camera.py
custom_components/frigate/config_flow.py
custom_components/frigate/translations/en.json
custom_components/frigate/views.py
requirements.txt
tests/test_config_flow.py

* Avoid urllib munging and use YARL instead which makes it harder to make mistakes.
* Add config validation to make sure we get a valid URL (as we subsequently parse the URL)

Improve URL handling

---

custom_components/frigate/__init__.py
custom_components/frigate/binary_sensor.py
custom_components/frigate/camera.py
custom_components/frigate/sensor.py
custom_components/frigate/switch.py

* Extract common logic out of frigate entities for improved readability and maintainability (wanted to wait until after unittests were done, to reduce likelihood of breaking something).
* Net code size -= 50 lines.

Entity refactor

---

custom_components/frigate/__init__.py
custom_components/frigate/api.py
custom_components/frigate/binary_sensor.py
custom_components/frigate/camera.py
custom_components/frigate/config_flow.py
custom_components/frigate/media_source.py
custom_components/frigate/sensor.py
custom_components/frigate/switch.py
custom_components/frigate/views.py
tests/test_api.py
tests/test_binary_sensor.py
tests/test_camera.py
tests/test_config_flow.py
tests/test_init.py
tests/test_media_source.py
tests/test_sensor.py
tests/test_switch.py
tests/test_views.py

* Encapsulate errors from the API client.
* Remove superfluous logging, standardize logging names with HomeAssistant core.
* Remove several broad Exception catches.

Improved logging and error handling

---

custom_components/frigate/media_source.py
tests/test_media_source.py

* Improve recording error handling & testing of unexpected media names.
* Remove last instance of "except Exception".

Get rid of the last broad exception usage

---

custom_components/frigate/media_source.py

Note: NOT ready for review, needs https://github.com/blakeblackshear/frigate-hass-integration/pull/88 first, as this builds on that. I'll mark this ready for review when/if that gets merged.
Context: This is part of an effort to allow this integration to support multiple Frigate servers.
Today, `media_source.py` caches the `/events/summary?has_clip=1` for 60 seconds. This caching introduces a number of instance variables that are specific to one server. Either this caching would need to be re-keyed to support multiple servers, or removed. I believe the latter is the best choice, as it:
* Removes code-complexity and hard to test time-based behavior.
* Provides low value anyway. One entry from that endpoint is about 100b. If we imagine 5 years worth of data, for ten cameras/zones, that's `5 …

Remove event summary cache

---

custom_components/frigate/media_source.py
tests/test_media_source.py

* Resolves: https://github.com/blakeblackshear/frigate-hass-integration/issues/102

0 is an hour too

---

.github/labels.yml
.github/release-drafter.yml
.github/workflows/labeler.yml
.github/workflows/release-drafter.yml

* Automatically maintain labels.
* Automatically draft release notes based on labels.

Add release-drafter and labeler

---

.github/release-drafter.yml

Use lady_beetle instead of beetle as the bug emoji

---

custom_components/frigate/media_source.py
tests/test_media_source.py

Fix subtle int validation bug impacting browsing of recordings at 00:XX:YY

---

README.md

Update README.md to show mqtt dependency

---

custom_components/frigate/manifest.json

* Bump up one version to include the latest (minor) features.

Bump version to v2.1.0 .

---

custom_components/frigate/api.py

Do not specify loop parameter to remove deprecation logspam

---

custom_components/frigate/camera.py

Use the new `async_camera_image` interface to avoid logspam

---

custom_components/frigate/__init__.py
tests/test_init.py

Remove devices no longer found on the Frigate server

---

custom_components/frigate/__init__.py

MQTT change to support >= HA 2022.3.0

---

custom_components/frigate/camera.py
tests/test_camera.py

#232: Camera state not updating when toggling recordings

---

custom_components/frigate/const.py
custom_components/frigate/diagnostics.py
tests/test_diagnostics.py

Add diagnostics

---

custom_components/frigate/__init__.py
custom_components/frigate/views.py
tests/test_views.py

Depends on this PR: https://github.com/dermotduffy/frigate-hass-card/pull/619

Proxy the new Frigate recordings API (allows the card to support recordings)

---

custom_components/frigate/__init__.py
custom_components/frigate/manifest.json
tests/test_init.py

Fix entity rename for unusually named entities

---

.devcontainer/config/configuration.yaml
.devcontainer/config/preconfig/.storage/auth
.devcontainer/config/preconfig/.storage/auth_provider.homeassistant
.devcontainer/config/preconfig/.storage/core.config_entries
.devcontainer/config/preconfig/.storage/onboarding
.devcontainer/config/www/.gitignore
.devcontainer/devcontainer.json
.devcontainer/frigate.yml
.devcontainer/post_create.sh
.devcontainer/preconfig.sh
.vscode/settings.json
docker-compose.yml
docker/Dockerfile.dev

- Preconfigure Home Assistant
- Administrator (`admin`/`admin` user)
- Bypass onboarding
- MQTT integration
- Frigate integration
- Preconfigure Frigate
- Add a demo camera
- Lots of other things
https://user-images.githubusercontent.com/29582865/172961717-96f6b255-bf05-44a3-b82d-927dfc997350.mp4

Preconfigure HA and Frigate in devcontainer

---

docker-compose.yml

Bump docker-compose forwarded ports

---

.devcontainer/config/configuration.yaml
.devcontainer/config/preconfig/.storage/frontend.user_data_1141ee80e0a647c1a4687d0b7631a019
.devcontainer/config/preconfig/.storage/lovelace
.devcontainer/config/preconfig/.storage/lovelace_resources
.gitignore
.vscode/launch.json
docker-compose.yml

* Automatic login.
* User has "advanced" options enabled.
* Dashboard showing Frigate entities (can be overridden in other repos that use this devcontainer, e.g. card)
* Launcher from vscode.

Improve devcontainer environment

---

custom_components/frigate/camera.py

Reverts blakeblackshear/frigate-hass-integration#283
@uvjustin FYI

Revert "Set use_wallclock_as_timestamps stream option"

---

custom_components/frigate/api.py
custom_components/frigate/views.py
custom_components/frigate/ws_api.py
tests/test_api.py
tests/test_ws_api.py

* A future PR will remove the recordings HTTP view (after the next card release).

Add recordings WS endpoint

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/build.yaml

As it's the one used in HA 2022.7.0

Upgrade Python from 3.9 to 3.10

---

requirements.txt
requirements_dev.txt
tests/test_media_source.py

As the repo is now tested with Python 3.10.

Upgrade Home Assistant to 2022.7

---

custom_components/frigate/ws_api.py
tests/test_ws_api.py

Related card PR: https://github.com/dermotduffy/frigate-hass-card/pull/796

Revert "Restore JSON decode for ws_api (#329)"

---

custom_components/frigate/manifest.json

Preparing for imminent full release of Frigate v0.11 .
@NickM-27 
@blakeblackshear

Bump version to v3.0.0 .

---

custom_components/frigate/camera.py
custom_components/frigate/config_flow.py
custom_components/frigate/const.py
tests/__init__.py
tests/test_camera.py
tests/test_config_flow.py

This will require frigate 0.12.0

FEAT: Support Frigate RTSP Restream

---

custom_components/frigate/sensor.py
tests/__init__.py
tests/test_sensor.py

FEAT: Support sensors for per-process CPU usage

---

README.md

**Upstream breaking change:** https://github.com/badges/shields/issues/8671

Update build badge due to upstream breaking change

---

custom_components/frigate/binary_sensor.py

Fix binary sensor classes

---

custom_components/frigate/__init__.py
custom_components/frigate/api.py
custom_components/frigate/config_flow.py
custom_components/frigate/manifest.json
custom_components/frigate/media_source.py
custom_components/frigate/ws_api.py
requirements.txt
requirements_dev.txt
tests/test_api.py
tests/test_media_source.py
tests/test_ws_api.py

Fixes https://github.com/blakeblackshear/frigate-hass-integration/issues/393

Use the HA timezone setting for requesting recordings, provide timezone to event summary

---

custom_components/frigate/__init__.py

I realized that on startup the birdseye entity would be removed, my bad for missing this originally

Don't remove birdseye on startup

---

custom_components/frigate/manifest.json

After https://github.com/blakeblackshear/frigate-hass-integration/pull/422 I think we should be ready for the next beta

Update to beta4

---

custom_components/frigate/sensor.py
tests/test_sensor.py

Closes https://github.com/blakeblackshear/frigate-hass-integration/issues/429

Fix handling of GPU error conditions in sensors

---

custom_components/frigate/api.py
custom_components/frigate/manifest.json
custom_components/frigate/media_source.py
custom_components/frigate/ws_api.py
tests/test_api.py
tests/test_media_source.py
tests/test_ws_api.py

* Related: https://github.com/dermotduffy/frigate-hass-card/issues/900

Allow API callers (e.g. the card) to search via sub_labels

---

README.md

Update UI navigation path for HACS

---

custom_components/frigate/camera.py
tests/test_camera.py

Closes https://github.com/blakeblackshear/frigate-hass-integration/issues/490

Include attributes for client id and camera name

---

custom_components/frigate/camera.py
custom_components/frigate/config_flow.py
custom_components/frigate/const.py
custom_components/frigate/translations/en.json
tests/test_camera.py
tests/test_config_flow.py

Enable WebRTC in Frigate camera entities. Implements #550

Add WebRTC streaming to camera entities

---

custom_components/frigate/sensor.py
tests/test_sensor.py

Fix `TEMP_CELSIUS` deprecation

---

custom_components/frigate/icons.py
custom_components/frigate/switch.py
tests/__init__.py
tests/test_icons.py
tests/test_switch.py

This PR adds a switch to the integration for autotracking cameras. The backend PR is: https://github.com/blakeblackshear/frigate/pull/8630

Add a switch for autotracking cameras

---

custom_components/frigate/translations/fr.json

Add French translation

---

custom_components/frigate/icons.py
custom_components/frigate/sensor.py
tests/__init__.py
tests/test_sensor.py

closes https://github.com/blakeblackshear/frigate-hass-integration/issues/549

Add sound sensor

---

custom_components/frigate/manifest.json

Many users have requested the sound sensor so I think now is a good time to do a quick release before things that require frigate 0.14 start coming in

Update to 5.1.0

---

custom_components/frigate/translations/ca.json

Add catalan translations

---

custom_components/frigate/services.yaml

Fixes blakeblackshear/frigate-hass-integration#657

Fixes playback_factor selectable value in services.yaml

---

custom_components/frigate/__init__.py
custom_components/frigate/binary_sensor.py
custom_components/frigate/camera.py
custom_components/frigate/switch.py
tests/test_switch.py

* Partially addresses #667 
* As of writing, issue with `motion` switch remains but that may be a separate unrelated problem.

Fix HA incompatibility: always try to decode MQTT payloads

---

custom_components/frigate/manifest.json
custom_components/frigate/views.py
tests/test_views.py

The proxy for preview gifs can be added before 0.14 is fully released since it is not a breaking change

Merge dev into master for 5.3.0 release

---

custom_components/frigate/manifest.json

Need to do a release for the next HA update

Update version to 5.4.1

---

README.md
custom_components/frigate/manifest.json

* [Motivation](https://github.com/home-assistant/core/issues/129990#issuecomment-2495202466)

docs: Update integration maintainers list

---

custom_components/frigate/manifest.json
custom_components/frigate/media_source.py
requirements.txt
requirements_dev.txt
tests/test_media_source.py

fix: Don't block on loading tzinfo objects

---

custom_components/frigate/config_flow.py
tests/test_config_flow.py

feat: Add support for `reconfigure`

---

custom_components/frigate/camera.py
tests/__init__.py
tests/test_camera.py

Closes https://github.com/blakeblackshear/frigate-hass-integration/issues/858

Implement camera toggle

---

custom_components/frigate/__init__.py
custom_components/frigate/manifest.json

Fix incorrect access of 0.16 only property

---

custom_components/frigate/__init__.py
custom_components/frigate/camera.py
custom_components/frigate/manifest.json
custom_components/frigate/sensor.py

fixes https://github.com/blakeblackshear/frigate-hass-integration/issues/898

Fix handling of old Frigate version that used int type

---

custom_components/frigate/translations/zh-Hans.json

feat: add chinese i18n file
