custom_components/frigate/camera.py, custom_components/frigate/const.py
This PR updates the snapshot camera's state based on the cameras image.  This makes using a conditional card to display snapshots much easier.
=> Snapshot camera state based on image

custom_components/frigate/manifest.json
Starting with Home Assistant 2021.3.0, components must include a version in the manifest
=> Add version to manifest.json

custom_components/frigate/config_flow.py, custom_components/frigate/const.py, custom_components/frigate/translations/en.json, requirements.txt, requirements_dev.txt, tests/__init__.py, tests/conftest.py, tests/test_config_flow.py
* Add basic skeleton to support tests (e.g. `conftest.py`, `requirements*`)
* Add tests for `config_flow.py` as a first demo test (test coverage for this file -> 100%)
* Simplify `config_flow.py` a bit for readability (including removing checks for mqtt, which is unnecessary since the dependency is in `manifest.json`).
For the record, output:
```
(~/src/frigate-hass-integration) $ pytest --cov-report=term-missing --cov=custom_components/frigate tests/
Test session starts (platform: linux, Python 3.8.5, pytest 6.2.4, pytest-sugar 0.9.4)
rootdir: src/frigate-hass-integration
plugins: forked-1.3.0, cov-2.10.1, xdist-2.1.0, aiohttp-0.3.0, test-groups-1.0.3, timeout-1.4.2, sugar-0.9.4, homeassistant-custom-component-0.3.2, requests-mock-1.8.0
collecting ... 
tests/test_config_flow.py ✓✓✓ …
```
=> Add basic test structure and tests for config_flow

custom_components/frigate/__init__.py, custom_components/frigate/binary_sensor.py, custom_components/frigate/camera.py, custom_components/frigate/media_source.py, custom_components/frigate/sensor.py, custom_components/frigate/switch.py, tests/test_binary_sensor.py
Home Assistant devices are intended to represent physical items that can be assigned to `areas` ([docs](https://developers.home-assistant.io/docs/device_registry_index/#what-is-a-device)). Rather than a single Frigate device, instead expose each Frigate camera as a device -- this allows:
* Convenient grouping of entities belonging to a single camera (as there are a considerable number of entities this grouping eases exploration of the entities)
* Assignment of devices to home assistant areas (after setup the user is prompted to assign devices to areas).
Entities not related to a camera (e.g. CPU inference speed) are still tied to the "parent" Frigate device. Note: Another variant of this would be to have no "parent" device at all.
=> Create more granular devices

.github/workflows/build.yaml, .pre-commit-config.yaml
* [**Cleanup**] We no longer need to trigger the build on the 'build' branch, since it's now merged into master.
* [**Fix**] Unlike Home Assistant Core (where all commits are to `dev` branch) we do need to allow commits to master. This is why [your merge failed the pre-commit](https://github.com/blakeblackshear/frigate-hass-integration/runs/2760071201?check_suite_focus=true).
=> Minor build fixes

.github/workflows/build.yaml
Add code coverage instrumentation. I find tracking the data encourages me to keep the coverage high!
This requires a [codecov](https://about.codecov.io/sign-up/) account and giving it access to this repo, which you may or may not want/have. If you'd rather use a different coverage system, or not track coverage, no worries. Signing up gives us two things:
* Instrumentation ([random example from another integration I maintain](https://app.codecov.io/gh/dermotduffy/hass-motioneye)).
* A badge to shame us into maintaining good coverage <img width="103" alt="Screen Shot 2021-06-06 at 7 59 37 PM" src="https://user-images.githubusercontent.com/1136829/120953440-ce010480-c701-11eb-9bd9-d9efed3684e9.png">
=> Add code coverage tracking (codecov)

custom_components/frigate/media_source.py
[One of my earlier PRs](https://github.com/blakeblackshear/frigate-hass-integration/pull/63/files#diff-c0c9bfdb652d2f05cf484016f9d05d83d62418f56702111b9313f99f2d137a3dR596) introduced a subtle bug in `_count_by` that the (still in progress) `media_source.py` unittests found (yay unittests). 
d["camera" ] (and label, zone) is a list, not a string, so this invalid "style fix" had the effect of causing count_by to undercount for cameras/labels/zones.
```py
>>> "steps" in ("", ["steps"])
False
```
Unittest PR will come later, I just wanted to get head repaired in the meantime in case it costs someone time debugging.
=> Fix subtle count-by bug

custom_components/frigate/api.py, requirements_dev.txt, tests/test_api.py
To get this into Core, `FrigateApiClient` will need to be moved to a separate repo at a later date. As such, these API tests are written to not rely on HomeAssistant directly.
```
collecting ... 
tests/test_api.py ✓✓✓✓✓✓✓                                                                                                                                                                    20% ██        
tests/test_binary_sensor.py ✓✓✓✓                                                                                                                                                             31% ███▎      
tests/test_camera.py ✓✓✓✓                                                                                                                                                                    43% …
```
=> Test Coverage #7: API

custom_components/frigate/media_source.py, tests/test_media_source.py
Change the default date/time format to the Home Assistant Core standard (ISO 8601) and the time format to 24h. This is a purely subjective choice, and will make some people unhappy -- nevertheless I think this better aligns with the HA default. 
Notes:
* There is no way to get the [Home Assistant date/time format settings](https://www.home-assistant.io/blog/2021/06/02/release-20216/#time-format-settings) from the frontend into an integration, it is purely used on the frontend to localize entity states (e.g. a sensor with a date value). For raw strings (e.g. media browser) being sent from an integration to the frontend, there are no apparent localization opportunity.
Other options:
* Leave it as-is, US-centric times and UNIX locale tied dates.
* Add a config_flow option to allow datetime …
=> Change date formats to ISO 8601 and time formats to 24h.

custom_components/frigate/views.py
It is better to only proxy the minimum surface possible -- I don't think methods other than GET are likely used in this context.
=> Only proxy GET requests

custom_components/frigate/media_source.py, tests/test_media_source.py
* Convert from string manipulated identifiers to structured data identifiers (`attr.s`) in order to:
* Encapsulate serialization/deserialization of the identifiers in a single place, to allow easier future modifications of the identifiers (which I hope to take advantage of shortly).
* Improve code readability by not having to copy the strings all over the place.
* Significantly improved validation of identifiers earlier in the code (vs something surprising breaking later).
* If people have copied recording  or clips identifiers, they should continue to work.
=> Convert media source identifiers to structured data

custom_components/frigate/__init__.py, custom_components/frigate/binary_sensor.py, custom_components/frigate/camera.py, custom_components/frigate/config_flow.py, custom_components/frigate/media_source.py, custom_components/frigate/sensor.py, custom_components/frigate/switch.py, custom_components/frigate/translations/en.json, tests/__init__.py, tests/test_binary_sensor.py, tests/test_camera.py, tests/test_config_flow.py, tests/test_init.py, tests/test_sensor.py, tests/test_switch.py, tests/test_views.py
* Change the `unique_id` of all Frigate entities. This is a *major* change that risks breaking every Frigate entity and should be reviewed very carefully.
* Use a "big-endian" unique_id scheme `<config entry id>:<class descriptor>:<entity descriptive name>`. This unique_id is internal to HomeAssistant only, and links two HomeAssistant objects (config entries and entities) -- `<config entry id>` is absolutely the right choice here IMO, despite the discussion on #91 around which URL path to use: due to the cost/complexity of changing these identifiers, they should be as "insulated" as possible. A user will never see these identifiers.
* Attempt to do this in a backwards compatible way via a unittested config flow migration.
* Add unittests for unique_ids.
* While at it, address a silly …
=> Migrate to Frigate ConfigEntry v2

custom_components/frigate/__init__.py, custom_components/frigate/api.py, custom_components/frigate/binary_sensor.py, custom_components/frigate/camera.py, custom_components/frigate/config_flow.py, custom_components/frigate/const.py, custom_components/frigate/media_source.py, custom_components/frigate/sensor.py, custom_components/frigate/switch.py, custom_components/frigate/translations/en.json, custom_components/frigate/views.py, requirements.txt, tests/__init__.py, tests/test_api.py, tests/test_config_flow.py, tests/test_init.py, tests/test_media_source.py, tests/test_views.py
Update the integration to support multiple Frigate instances is suitably configured. Highlights:
* Media browser: Uses the new (https://github.com/blakeblackshear/frigate-hass-integration/pull/88) structured identifiers to seamlessly pass the config entry through the clip search functionality.
* Clean up the `data` dictionary for the integration so it is indexed by config entry id only, and have a clean consistent dict under each entry.
* Full backwards compatibility for both views and media browser -- if no "frigate instance id" is specified, and only one Frigate instance configured, that one is used by default. If multiple Frigate are configured, there is no default.
Update: The MQTT `client_id` field (and not the config entry id) is used to differentiate between frigate server …
=> Support multiple Frigate instances

.vscode/settings.json, custom_components/frigate/camera.py, custom_components/frigate/config_flow.py, custom_components/frigate/const.py, custom_components/frigate/translations/en.json, tests/test_camera.py, tests/test_config_flow.py
Add an advanced option for the integration, that allows the RTMP path to be overriden. This could be useful if the RTMP port is a different value, or is running behind a reverse proxy. The template supports access to the Frigate camera configuration, so for example a value like:
```rtmp://host.wherever:9999/live/{{ name }}```
... would access the camera name.
A simpler version of this would just be to support setting a different port, but I think this is more extensible. This effectively replaces https://github.com/blakeblackshear/frigate-hass-integration/pull/32 .
=> Add a template option to allow the RTMP path to be overridden

.github/workflows/build.yaml, .pre-commit-config.yaml, custom_components/frigate/__init__.py, custom_components/frigate/api.py, custom_components/frigate/binary_sensor.py, custom_components/frigate/camera.py, custom_components/frigate/config_flow.py, custom_components/frigate/media_source.py, custom_components/frigate/sensor.py, custom_components/frigate/switch.py, custom_components/frigate/views.py, pyproject.toml, requirements.txt, requirements_dev.txt, tests/__init__.py, tests/test_api.py, tests/test_binary_sensor.py, tests/test_camera.py, tests/test_media_source.py, tests/test_sensor.py, tests/test_switch.py, tests/test_views.py
* Make code "mypy clean": Didn't find anything major broken, but several incorrect/missing type annotations.
* Use ~stock Home Assistant Core mypy configuration (as Home Assistant doesn't offer type hints to custom integrations, this requires some mypy warnings to be explicitly marked ignored, e.g. inheriting from an untyped class).
* Have pre-commit run mypy by default.
=> Add strict type checking

custom_components/frigate/views.py
Ran into a weird problem when I used an SSL reverse-proxy in front of my setup, a HTTP 421 (had to look it up: "421 Misdirected Request") =>
* When I make the request to the proxied URLs, the host header is for the Home Assistant instance.
* This then get copied into the outbound request for Frigate, which the reverse-proxy then compares against the SSL cert intended for use in front of Frigate -- and finds they don't match -- and returns 421.
Do not explicitly override the host header, leave it unset.
=> Do not set host header on proxied requests

custom_components/frigate/config_flow.py, custom_components/frigate/const.py, custom_components/frigate/translations/en.json, custom_components/frigate/views.py, tests/test_config_flow.py, tests/test_views.py
- Add an option to reject requests to the notifications proxy, to eliminate any potential privacy issues (as small as the chances of guessing an event-id would be).
- Resolves: https://github.com/blakeblackshear/frigate-hass-integration/issues/44
- Does not disable the `/clips/` and `/recordings/` endpoints, as they are authenticated.
This also fixes a bug that required the RTML_URL_TEMPLATE option to be set to a non-empty value. Once set, the HA frontend would not allow it to be unset.
=> Add an option to disable the unauthenticated notifications proxy

custom_components/frigate/__init__.py
* Resolves: https://github.com/blakeblackshear/frigate-hass-integration/issues/104
=> Remove listener on entry unload to avoid multiple listeners.

custom_components/frigate/views.py, tests/test_views.py
When viewing clips  an occasional "ConnectionResetError: Cannot write to closing transport" spams  the logs. Cleanly catch and handle these exceptions:
* Resolves: https://github.com/blakeblackshear/frigate-hass-integration/issues/1
=> Cleanly handle connection resets

custom_components/frigate/camera.py, custom_components/frigate/config_flow.py, custom_components/frigate/const.py, custom_components/frigate/translations/en.json, tests/test_camera.py, tests/test_config_flow.py
- Add an option to allow the user to specify the height of their live camera static snapshots, vs the default of 277. A value of 0 will not specify any value in the request to Frigate, which appears to return the camera default.
- Resolves: https://github.com/blakeblackshear/frigate-hass-integration/issues/19
=> Add an option to allow specifying camera static image size

custom_components/frigate/__init__.py, custom_components/frigate/binary_sensor.py, custom_components/frigate/camera.py, custom_components/frigate/sensor.py, custom_components/frigate/switch.py, requirements.txt
An import path was changed on the HomeAssistant dev branch. Update our import to work both pre/post this change to ensure our versions are not coupled. After a suitable period of time post launch of  2021.8.0, this can be ~removed.
=> Changes for HA >= 2021.8.0.dev0

custom_components/frigate/api.py, custom_components/frigate/media_source.py, tests/test_api.py, tests/test_media_source.py
* Add snapshot  support for the media browser by introducing a new FrigateMediaType enum, and adding it to the  existing  identifier.
* Take the opportunity to be more meticulous in choice of media class/type.
* Update necessary test coverage.
* Closes #112
=> Support snapshots in the media browser

custom_components/frigate/manifest.json
Bump version to v1.1.0 .
* Increment the minor number (1.0.6 -> 1.1.0) to indicate this is a significant change in functionality since the last release, although in a backwards compatible way.
* In particular https://github.com/blakeblackshear/frigate-hass-integration/pull/92 is a significant underlying change to how the integration represents itself on disk.
=> Bump version to v1.1.0 

custom_components/frigate/__init__.py, requirements.txt
* Rather than trying to precisely identify the set of versions that are before/after the type change, just try to import both -- starting with the new one, and falling back to the old one.
* Verified working on the Home Assistant `2021.8.0b5` (which was failing before)
* Closes #119
=> Fix broken import experienced by users of certain versions of HomeAssistant

custom_components/frigate/manifest.json
* Bump the version number (and then do a new pre-release) to pull in https://github.com/blakeblackshear/frigate-hass-integration/pull/120 , as otherwise the new version will not work for a segment of the intended audience.
=> Bump version to v1.1.1

README.md, info.md
* Sync the README features with the info.md features.
* Change the HACS logo to custom.
@blakeblackshear I somehow thought this integration was in HACS default already (rather than custom). Being in default will  show it up in the 'store' which may help drive usage / ease installation. Any objection to me adding it there?
=> Minor doc fixes to sync README and HACS info.md

custom_components/frigate/__init__.py, tests/test_binary_sensor.py
* We were not unsubscribing from the mqtt topic, which meant mqtt updates were triggering state updates, causing an appropriate log message:
```
Entity binary_sensor.zone_garage_on_property_bicycle_motion is incorrectly being triggered for updates while it is disabled. This is a bug in the frigate integration
```
Closes #128
=> Unsubscribe from mqtt topic on unload to resolve log spam on entity disable

custom_components/frigate/__init__.py, custom_components/frigate/camera.py, custom_components/frigate/config_flow.py, custom_components/frigate/const.py, custom_components/frigate/translations/en.json, requirements.txt, requirements_dev.txt, tests/conftest.py, tests/test_camera.py, tests/test_config_flow.py, tests/test_init.py, tests/test_views.py
* Leverage the new Home Assistant functionality to accept width/height parameters for image fetching.
* Retire the 'camera_image_height' option -- it will be automatically removed from Frigate config entries.
* Closes #138 
Breaking behavior:
* Previously, the 'camera_image_height' configuration option would dictate the height of all images captured from the camera (i.e. both lovelace, and `camera.snapshot` service).
* With this PR, by default, the maximum size will be returned unless specifically requested otherwise. Right now, the width/height choices are not yet externalized to the `camera.snapshot` service, so callers will only have the choice of 'full size'.
So why make this  change:
* The motivation for the option in the first place was to reduce the bandwidth / increase the speed …
=> Retire 'camera_image_height' option.

custom_components/frigate/__init__.py, custom_components/frigate/views.py, tests/test_views.py
* Add a general websocket proxy that we can use to proxy between HA <-> Frigate.
* Instantiate the (authenticated) proxy for JSMPEG proxying.
* Required to support: https://github.com/dermotduffy/frigate-hass-card/issues/18
=> Add a websocket proxy to support JSMPEG on the Frigate Lovelace card

custom_components/frigate/media_source.py, custom_components/frigate/views.py, tests/test_media_source.py, tests/test_views.py
* Adapts the integration to work with long-running "in-progress" events (i.e. no end-time).
* Fixes in media_source to show the duration as (now - start_time) when the end_time isn't available.
* Fixes the snapshot proxy to use `/api/events/<eventid>/snapshot.jpg` (on the Frigate backend) as the destination of the request, with`/api/frigate/snapshot/<eventid>` as the Home Assistant entry point.
* By using '/snapshot/' as the entry point, I'd hope to avoid needing to change this again even if the backend path changes (we'd just swap out the destination).
* An **alternative** choice would be to mirror the Frigate backend path, i.e. the Home Assistant endpoint would be `/api/events/<eventid>/snapshot.jpg` to match the server.
* Closes …
=> Fixes to support in-progress events (Frigate 0.10+)

custom_components/frigate/switch.py, tests/test_switch.py
Several users have experienced the frigate switches turning off unexpectedly. I think this is due to retain=True for the command topic. In Frigate's code, retain is only ever set to retain on the state topic.
=> use retain=False for command topic

custom_components/frigate/media_source.py, tests/test_media_source.py
The Home Assistant frontend will just ignore the extra metadata, but clients that understand Frigate will be able to offer extended functionality (i.e. the Frigate Card).
=> Attach the raw Frigate event to the BrowseMediaSource

custom_components/frigate/__init__.py, custom_components/frigate/camera.py
The all part was working except it was creating a `camera.office_all` for example which it shouldn't
=> Filter all cam

custom_components/frigate/__init__.py, custom_components/frigate/binary_sensor.py, custom_components/frigate/camera.py, custom_components/frigate/sensor.py, custom_components/frigate/switch.py
This one adds the "Visit Device" button to each of the device pages! For specific cameras, it should open to that camera's page in the Frigate UI, but for the "master" device and zones, it will open to the main Frigate homepage.
=> :sparkles: - Add device configuration URLs

custom_components/frigate/sensor.py, custom_components/frigate/switch.py
This would organize the entities created a little bit further, with the "Detect", "Recordings", and "Snapshots" switches being categorized under "Configuration", and the various FPS sensors being under "Diagnostics". Camera entities, including the snapshots, and the motion and tracked objects sensors will stay under "Sensors".
=> :sparkles: - Add entity categories

custom_components/frigate/__init__.py, custom_components/frigate/binary_sensor.py, tests/__init__.py, tests/test_binary_sensor.py, tests/test_init.py
* Renames entities previously known as `binary_sensor.kitchen_person_motion` to `binary_sensor.kitchen_person_occupancy`. The old name was a misnomer. All automations and templates that used the old entity_id must be updated manually.
* Introduces a new motion sensor entity (not associated with objects): `binary_sensor.kitchen_motion`. This entity is disabled by default.
Parent frigate PR: https://github.com/blakeblackshear/frigate/pull/3152
This adds support for a true motion sensor. 
1. I know (from other integrations / requests) that users will likely not work well with the direct data coming from frigate which will rapidly switch between True / False. Happy to provide specific examples, but it seems users will likely expect this motion sensor to behave in the fashion where it will be …
=> 💥 Support for general motion sensor

hacs.json
Hey,
HACS check does not support any more `domains` and `iot_class` in the manifest (hacs.json). And also they are removed from the documentation (https://hacs.xyz/docs/publish/start#hacsjson)
If removing them, HACS action will not provide errors you currently have:
`Error:  <Validation hacs_manifest> failed:  extra keys not allowed @ data['domains']`
And yes, if only remove `domains`, next time it will show a problem with `iot_class`
Have a nice day!
P.S. This was checked on my HA integration: [link to the last checks](https://github.com/Vaskivskyi/ha-asusrouter/actions/workflows/build.yaml)
=> Remove deprecated HACS manifest values

custom_components/frigate/config_flow.py, custom_components/frigate/const.py, custom_components/frigate/media_source.py, custom_components/frigate/translations/en.json, tests/test_config_flow.py, tests/test_media_source.py
=> Ability to disable media browser

custom_components/frigate/camera.py
HA's stream has an unfortunate "feature" where bad timestamps can cause an assertion error, bringing down the whole process. This can be worked around by having HA rewrite the timestamps using ffmpeg's `use_wallclock_as_timestamps` flag.
This problem was encountered by @drthanwho who noticed the issue when rebooting cameras. It appears the rtmp stream is not restarted when the cameras are restarted, so an alternative to this PR may be to set up the nginx rtmp module in frigate with the [play_restart](https://github.com/arut/nginx-rtmp-module/wiki/Directives#play_restart) option set to on.
=> Set use_wallclock_as_timestamps stream option

.devcontainer/frigate.yml
@felipecrs Too many things with 'demo' in the name ;-) Suggest we rename the Frigate camera so the resultant entity in HA is just `camera.frigate`. Opinions?
=> Rename the devcontainer Frigate camera

custom_components/frigate/views.py
* Casting the Frigate card results in a HTTP fetch for recordings which is a cors request in that case, which causes the Frigate integration to crash/assert without this PR.
=> Prevent assert from cors library on preparing response to cors request

custom_components/frigate/__init__.py, custom_components/frigate/views.py, tests/test_views.py
* Remove the unnecessary HTTP view for recordings API access. The integration now exposes this API over websocket instead. The only known user of the HTTP view (the card) has already been moved over (in code, not yet build).
Keeping as draft until the card build is released.
**Update**: New card build no-longer relies on recordings over HTTP: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v4.0.0-rc.2
=> Remove the HTTP view for recordings API (WS still available)

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/home_assistant_run.sh, .devcontainer/post_create.sh, .devcontainer/set_dot_env.sh, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, docker-compose.yml
- Drops the necessity of statically forwarding ports in Remote SSH scenarios (@dermotduffy can you please test this?)
- Drops the necessity of statically set high ports due to possible conflicts for containers (@dermotduffy can you please test this too?), since now port forwarding is handled by VS Code, which will auto-detect the best port to use
- Add docker to devcontainer, as in the Card
- Refs https://github.com/microsoft/vscode-dev-containers/pull/1522
- Allow Home Assistant to start in debug mode (I hope to merge this in upstream later)
- Add set_dot_env.sh which can be reused later in the Card
- Configure Python debugger which attaches to the Home Assistant process running in the HA container, and everything can be used as expected, like break points and so.
- Drops the …
=> Improve devcontainer experience (e.g. adds python debugging, improves port forwarding)

custom_components/frigate/api.py, custom_components/frigate/ws_api.py, tests/test_ws_api.py
This PR avoids decoding from json when proxying to the ws api.
=> Avoid decoding json when proxying over ws

custom_components/frigate/views.py
iter_any() seems better to use as it allows us to send out whatever we have so far instead of looping through each chunk. I do not have a good setup to test this though (I use H.265 so don't actually use Frigate much).
=> Use iter_any() instead of iter_chunked()

custom_components/frigate/__init__.py, custom_components/frigate/api.py, custom_components/frigate/media_source.py, custom_components/frigate/views.py, tests/fixtures/events_front_door.json, tests/test_media_source.py, tests/test_views.py
:boom: Frigate card users will require the latest card build to continue to have working thumbnails.
@blakeblackshear This is an alternative implementation which uses http for the thumbnails instead of getting them upfront and sending them in the BrowseMediaSource.
The downside of this is that it doesn't fetch the images upfront, so there's going to be more latency.
With small thumbnails, this is probably a worse solution, but if there's a move to larger/more thumbnails this might be better.
Note - this does seem to raise a problem with HA's ip ban middleware. I'll try to put a fix in for that over there.
=> Fetch thumbnails over http instead of using base64 embedded thumbnails

custom_components/frigate/media_source.py, custom_components/frigate/views.py, tests/test_media_source.py, tests/test_views.py
Chromium's service worker cache [exhibits poor performance](https://bugs.chromium.org/p/chromium/issues/detail?id=682677) when using ignoreSearch:true (which is necessary for paths using HA's auth). This makes it unsuitable for thumbnails especially as they are 1) numerous (the latency appears to increase linearly with number of cached objects) and 2) small (there's not much data usage savings, so latency would have been the main benefit, but even that doesn't appear to be a benefit here).
This PR removes "static" from the ThumbnailsProxyView path name. The service worker should now treat it with the NetworkOnly() strategy.
=> Remove "static/" from ThumbnailsProxyView path

custom_components/frigate/ws_api.py, tests/test_ws_api.py
* Was breaking the card which was just receiving the raw string: https://github.com/dermotduffy/frigate-hass-card/issues/790
* Makes sense to decode this on the HA side and the ws_api caller just receives the decoded data.
* Related: https://github.com/blakeblackshear/frigate-hass-integration/pull/321
=> Restore JSON decode for ws_api

custom_components/frigate/views.py
Passing the authSig in the query parameters is unnecessary and may prevent cache from working properly. Passing the authSig is only required for VodProxyView (so that the HLS manifests that get sent back have segment URLs that include the authSig).
=> Don't proxy authSig parameter unless necessary

custom_components/frigate/views.py
The nginx vod module actually works fine with H.265. This PR allows the Lovelace card to properly display H.265 clips.
(Frigate's own frontend doesn't work because it uses <strike>JSMPEG</strike> videojs.)
=> Update VodSegmentProxyView to allow mp4/m4s files

custom_components/frigate/config_flow.py, custom_components/frigate/const.py, custom_components/frigate/translations/en.json, custom_components/frigate/views.py, tests/test_config_flow.py, tests/test_views.py
Resolves #153 
The unauthenticated notifications proxy gives access to event data in
perpetuity. If a URL is shared or leaks, it is valid for the lifetime of
the event id.
This change allows the user to set an expiration time (in minutes) for
the notification event to be valid. After this time, the notification
proxy will not allow the event to be accessed, and the user will have to
go through the typical Frigate flow to retrieve snapshots/clips etc.
If the user sets the expiration time to 0 (default) this feature is
disabled.
=> Allow setting an expiration time for unauthenticated notification events

custom_components/frigate/api.py, custom_components/frigate/ws_api.py, tests/test_ws_api.py
**Usecase**: Allow the card to [in future] possibly replace calls to the main HA media browser and directly receive the events feed. Simple experimentation shows this is ~25% faster for the card to load events for the timeline than going via the HA media browser.
=> Export events over websocket

custom_components/frigate/sensor.py, tests/__init__.py, tests/test_sensor.py
Adds sensor for upstream https://github.com/blakeblackshear/frigate/pull/3931
=> Add sensor for gpu usage

custom_components/frigate/camera.py
The self._attr_is_streaming was set true from old config logic. This is a quick fix to enable streaming if the camera is present in go2rtc streams.
=> `_attr_is_streaming` should respect go2rtc streams

custom_components/frigate/api.py, custom_components/frigate/media_source.py, custom_components/frigate/ws_api.py, tests/test_api.py, tests/test_media_source.py, tests/test_ws_api.py
* Helps reduce number of calls to the backend.
* Integration itself should work seamlessly.
* This is a breaking change for any (unknown) external users of these APIs.
=> Change Frigate `api` and `ws_api` to multi selection instead of single selection

custom_components/frigate/update.py
This goes alongside https://github.com/blakeblackshear/frigate/pull/5208 to ensure that the HASS integration correctly handles the new "disabled" API response that occurs if the Frigate version update check is disabled.
=> Latest version check: add handling for "disabled"

custom_components/frigate/camera.py, tests/test_camera.py
Fixes #418 while https://github.com/AlexxIT/go2rtc/issues/194 isn't fixed (and while we don't know if it will be fixed or not).
=> Force AAC audio to be used in RTSP URL

custom_components/frigate/__init__.py, custom_components/frigate/camera.py, custom_components/frigate/media_source.py, custom_components/frigate/views.py, pyproject.toml, requirements.txt, requirements_dev.txt, tests/__init__.py, tests/test_api.py, tests/test_binary_sensor.py, tests/test_camera.py, tests/test_number.py, tests/test_sensor.py, tests/test_switch.py, tests/test_update.py
* Closes: https://github.com/blakeblackshear/frigate-hass-integration/issues/421
=> Fixes for Home Assistant 2023.1.7+, Python 3.9, Python 3.10

custom_components/frigate/camera.py, tests/test_camera.py
- This reverts commit b91d882a96b1fa4a45a4d7e9bb9329392e41fad6, which is no longer necessary since https://github.com/AlexxIT/go2rtc/issues/194 was fixed.
- Refs https://github.com/blakeblackshear/frigate-hass-integration/issues/418
=> Revert "Force AAC audio to be used in RTSP URL (#419)"

custom_components/frigate/config_flow.py
=> Fix typo in docstring in `config_flow.py`

custom_components/frigate/__init__.py, custom_components/frigate/const.py
In Frigate 0.13 along with Frigate+ there are certain labels (amazon, face, license_plate, etc.) which are not separately tracked objects and are ONLY attributes of another label (a person has a face, a car has a license plate, etc.)
Given that these labels are not treated as other objects, they will not have their own MQTT snapshots, object counts, etc. so they should be filtered out from the objects that are added.
=> Ignore attribute labels

custom_components/frigate/media_source.py, tests/fixtures/events_front_door.json, tests/test_api.py, tests/test_media_source.py
https://github.com/blakeblackshear/frigate/pull/6320 changed the events API to move `box`, `region`, `score` and `top_score` into a "data" sub-struct
=> Fix Home Assistant media viewer for new Frigate versions

custom_components/frigate/sensor.py, tests/__init__.py
Frigate 0.13 has added a new processes type for stats info on other processes. I don't think these make sense to be added into HA integration, so ignoring the key
=> Ignore processes

custom_components/frigate/manifest.json
There are no more new changes coming in for the frigate integration before frigate 0.13 beta, so creating the PR to bump the version. Not sure if it makes sense to leave in the dev branch until it makes it to stable or if the release process requires merging dev to master.
=> Set version to v5.0.0-beta.1

custom_components/frigate/__init__.py, tests/test_init.py
Fixes https://github.com/blakeblackshear/frigate-hass-integration/issues/543
=> Fix Error For Frigate Version With Leading 0 In Commit

custom_components/frigate/api.py, custom_components/frigate/ws_api.py, tests/test_api.py, tests/test_ws_api.py
* For https://github.com/dermotduffy/frigate-hass-card/issues/1163 .
=> Expose camera PTZ information over websocket

custom_components/frigate/manifest.json
Will be paired with upcoming frigate 0.13 beta 3, which should be ready in a day or two time. I believe this can be merged now and a release done in sync with the 0.13 beta 3 release
=> Update build to `5.0.0-beta.3`

custom_components/frigate/camera.py
https://developers.home-assistant.io/blog/2022/04/02/support-constants-deprecation
https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation/
related issue https://github.com/home-assistant/core/issues/106522
=> Fix camera supported_features to return CameraEntityFeature

custom_components/frigate/camera.py, tests/test_camera.py
Allow cameras to provide an HLS even if they're set up as WebRTC so they can work as a media source.
=> Allow HLS fallback in webrtc mode

custom_components/frigate/views.py
I setup basic auth in front of frigate with caddy and this is the only issue I have had. 
The thumbnail previews were broken in frigate-hass-card and
I was getting errors in home assistant logs "ValueError: Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL" I am passing basic auth in the url.
Removing the passed through AUTHORIZATION header, which I assume is for home assistant authorization and not needed for api calls on to frigate.... Fixed the issue.
=> Fix to allow basic auth in frigate-hass-card thumbnails

custom_components/frigate/media_source.py
fixes https://github.com/blakeblackshear/frigate-hass-integration/issues/600
=> Fix 0.12 events media browser failure

custom_components/frigate/media_source.py
Fix a bug where home assistant media browser fails to load clips if any have a `top_score` of zero.
The errors look like this:
```
File "/config/custom_components/frigate/media_source.py", line 774, in _browse_events
event_items = self._build_event_response(identifier, events)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/frigate/media_source.py", line 860, in _build_event_response
title=f"{dt.datetime.fromtimestamp(event['start_time'], DEFAULT_TIME_ZONE).strftime(DATE_STR_FORMAT)} [{duration}s, {event['label'].capitalize()} {int((event['data'].get('top_score') or event['top_score'])*100)}%]",
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```
This was mostly fixed in [this …
=> Fix media browsing bug with events where `top_score` is `0`

custom_components/frigate/manifest.json
Rely on the pytz version included with Home Assistant
closes #634
=> Unpin pytz version in manifest requirement

custom_components/frigate/__init__.py, custom_components/frigate/const.py, custom_components/frigate/ws_api.py, custom_components/frigate/ws_event_proxy.py, tests/test_ws_api.py
* Offer websocket-based frigate events subscriptions.
* These gymnastics are necessary to allow the Frigate card (or other theoretical subscribers) to dynamically respond to Frigate events, without needing HA admin privileges (necessary for either subscribing to triggers or non-core events).
Related:
- https://github.com/dermotduffy/frigate-hass-card/issues/1494
=> Add websocket Frigate events proxy

custom_components/frigate/media_source.py
See https://developers.home-assistant.io/blog/2024/09/23/constants-media-player-deprecation
Fix #725
=> Replace MEDIA_CLASS_ and MEDIA_TYPE_ with MediaClass and MediaType

custom_components/frigate/__init__.py
ConfigType to be used instead
Successor of #746 
Edit: this is backwards compatible
=> Fix Config import

custom_components/frigate/manifest.json, custom_components/frigate/views.py, requirements.txt, tests/test_views.py
* Remove all proxying logic to a separate library [`hass-web-proxy-lib`](https://github.com/dermotduffy/hass-web-proxy-lib)
* Remove all testing that is not pertinent to what is being proxied.
* This library can then be used by other integrations (e.g. [`hass-web-proxy-integration`](https://github.com/dermotduffy/hass-web-proxy-integration) ).
* No material changes to actual Frigate proxying intended, beyond certain requests returning `NOT_FOUND` instead of `BAD_REQUEST` .
=> refactor: Move proxy fuctionality to a common library

custom_components/frigate/manifest.json, requirements.txt
* Commit history of underlying library: https://github.com/dermotduffy/hass-web-proxy-lib/commits/main/
* Main difference: Removes [homeassistant](https://pypi.org/project/homeassistant/) library as a runtime dependency (see #762)
=> chore: Bump `hass-web-proxy-lib` to `v0.0.7`

custom_components/frigate/camera.py, tests/test_camera.py
- Refs https://github.com/blakeblackshear/frigate-hass-integration/pull/776#discussion_r1859123083
This partially reverts https://github.com/blakeblackshear/frigate-hass-integration/pull/776, ~but also handles the case when birdseye would not be streaming (important to remember that birdseye doesn't even have streaming enabled by default)~ (EDIT: this was a mistake, birdseye entity is not even added if `birdseye.restream` is not enabled).
The rationale is: indeed, it is possible to have cameras in Frigate without streaming capabilities (i.e. if you don't have the camera set in your go2rtc).
=> Correctly handle cameras that are not streaming

custom_components/frigate/__init__.py, custom_components/frigate/camera.py, custom_components/frigate/config_flow.py, custom_components/frigate/translations/en.json, requirements.txt, requirements_dev.txt, tests/test_camera.py, tests/test_config_flow.py, tests/test_init.py
- This partially reverts https://github.com/blakeblackshear/frigate-hass-integration/pull/774
- To be merged after #782
- Closes https://github.com/blakeblackshear/frigate-hass-integration/issues/759
=> Add back option to use Frigate-native WebRTC support

custom_components/frigate/camera.py, hacs.json, requirements.txt, requirements_dev.txt, tests/test_camera.py
=> Fix deprecated `frontend_stream_type` overwrite

custom_components/frigate/views.py, tests/test_views.py
This will make it so Safari users can play back clips using HLS directly
=> Add support for proxying HLS clips for events

custom_components/frigate/config_flow.py, tests/test_config_flow.py
Fix two issues (both my fault):
- In my [reconfigure PR](https://github.com/blakeblackshear/frigate-hass-integration/pull/802) I referred to the wrong step, breaking translations.
- In @loispostula 's [auth PR](https://github.com/blakeblackshear/frigate-hass-integration/pull/801), I suggested using `None` instead of empty strings -- turns out the frontend cannot serialize `vol.Any(str, None)`, so this PR retreats to the use of empty strings which the frontend can serialize.
=> Fix minor issues with authentication flow

custom_components/frigate/views.py, tests/test_views.py
After the initial HLS playlist is received, the browser will need to pull the actual video/audio ts segments which need to be proxied as well.
=> Fix proxying HLS

custom_components/frigate/const.py, custom_components/frigate/icons.py, custom_components/frigate/sensor.py, tests/__init__.py, tests/test_sensor.py
=> Add uptime sensor

custom_components/frigate/camera.py, tests/test_camera.py
Add a guard to the `create_event` and `end_event` action required fields
fixes #847
=> Add guard to `create_event` and `end_event` action required fields

custom_components/frigate/__init__.py, custom_components/frigate/api.py, custom_components/frigate/config_flow.py, custom_components/frigate/const.py, custom_components/frigate/translations/en.json, custom_components/frigate/translations/fr.json, tests/test_config_flow.py
This PR is to allow users to disable ssl validation on their frigate servers as some (truenas users to name some) will have https with self signed certs
I'm not sure if this is everything required to fix, but should at least be a start that someone with more experience could finish.
=> validate ssl option

custom_components/frigate/camera.py
As reported by @RamblinWreck77 in https://github.com/blakeblackshear/frigate-hass-integration/issues/808
Looks like the camera.py file uses a home assistant core helper function to create websession connections:
https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/aiohttp_client.py
check lines 113 and 115
it accepts an argument for verify_ssl so i think it can be fixed with these changes, would love a second opinion.
cheers.
nick.
=> fix camera connections

.github/workflows/build.yaml, pyproject.toml, requirements.txt, requirements_dev.txt, tests/test_config_flow.py
The data entry flow constants have been deprecated since 2022.7.0 and
were finally removed in 2025.1.0
Updates the tests to homeassistant 2025.4.1.
Fixes: #860
=> Migrate Tests to FlowResultType

custom_components/frigate/camera.py
This PR improves the cameras on/off disabled behavior so the state will be `Idle` in that case, and the camera will remain available so the turn_on action can still be called.
=> Improve disabled behavior

custom_components/frigate/camera.py
This resolves webrtc connection not working for authenticated endpoints. Note that it only seems to fix it once I actually click on the card.
Similarly, the card preview was the same issue, just for loading the picture.
=> camera: Make it correctly use auth headers for webrtc connections

custom_components/frigate/sensor.py, tests/test_sensor.py
This removes the need for Frigate to manually send a message to clear the sensors, and instead it will automatically be done by the integration
=> Add support for clearing plate and face sensors automatically

custom_components/frigate/sensor.py
- Creates fps sensors dynamically for all root level and camera level *_fps fields from /api/stats
- Preserves existing functionality
- Automatically creates new overall sensors with release of frigate PR# [19469](https://github.com/blakeblackshear/frigate/pull/19469)
=> Add sensor support for any fps type
